# Generated by Django 2.0.2 on 2018-03-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0008_auto_20180314_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleanuptools',
            unique_together={('tool', 'cleanup')},
        ),
    ]
