# Generated by Django 2.0.2 on 2018-03-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0010_auto_20180314_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanuptools',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
