# Generated by Django 2.0.2 on 2018-03-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0011_auto_20180315_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleanupTools',
            new_name='RequiredTools',
        ),
        migrations.AlterModelOptions(
            name='requiredtools',
            options={'verbose_name_plural': 'required tools'},
        ),
    ]
