# Generated by Django 2.0.2 on 2018-03-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0012_auto_20180320_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'tool categories',
            },
        ),
        migrations.AddField(
            model_name='requiredtools',
            name='tool_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanups.ToolCategory'),
        ),
    ]
