# Generated by Django 2.0.2 on 2018-03-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0014_auto_20180320_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cleanups.ToolCategory'),
        ),
    ]
