# Generated by Django 2.0.2 on 2018-03-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0015_auto_20180320_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='image',
            new_name='image_url',
        ),
    ]
