# Generated by Django 2.0.2 on 2018-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0016_auto_20180320_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tool',
            name='image_static_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
