# Generated by Django 2.0.2 on 2018-03-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0017_auto_20180320_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool_category',
            new_name='category',
        ),
    ]
