# Generated by Django 2.0.2 on 2018-04-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0018_auto_20180320_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='available',
            new_name='is_available',
        ),
    ]
