# Generated by Django 2.0.2 on 2018-04-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0021_auto_20180415_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanups', to=settings.AUTH_USER_MODEL),
        ),
    ]
