# Generated by Django 2.0.2 on 2018-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0022_auto_20180415_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
