# Generated by Django 2.0.2 on 2018-04-16 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0023_auto_20180416_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanup',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleanup',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
