# Generated by Django 2.0.2 on 2018-04-16 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0024_auto_20180416_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanup',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='cleanup',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='cleanup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
