# Generated by Django 2.0.2 on 2018-04-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0025_auto_20180416_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleanup',
            name='date',
        ),
    ]
