# Generated by Django 2.0.2 on 2018-04-16 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0026_remove_cleanup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanup',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('intersection', 'Intersection'), ('address', 'Address'), ('premise', 'Public Building'), ('landmark', 'Landmark')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
