# Generated by Django 2.0.2 on 2018-04-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanups', '0027_auto_20180416_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='query_string',
            field=models.CharField(blank=True, help_text='String used to query this location', max_length=200, null=True),
        ),
    ]
